export const defaultProducts = [
  {
    id: "foam-oil",
    slug: "foam-oil",
    name: "J'essence Vegan Foam Oil",
    category: "cleansing",
    volumeLabel: "150ml",
    shortDescription: "One-step cleansing for makeup and sunscreen routines.",
    description: "A gentle vegan foam oil selected for daily cleansing routines in warm Singapore weather.",
    imageUrl: "/images/foam-oil.png",
    unitPriceSgd: 8.99,
    packQuantity: 30,
    packPriceSgd: 269.7,
    unitWeightKg: 0.18,
    inventoryPacks: 20,
    active: true,
    purchaseEnabled: true,
    sortOrder: 10,
  },
  {
    id: "foaming-cleanser",
    slug: "foaming-cleanser",
    name: "J'essence Vegan Foaming Cleanser",
    category: "cleansing",
    volumeLabel: "200ml",
    shortDescription: "Soft daily face wash for a clean, comfortable finish.",
    description: "A soft foaming cleanser for everyday wash routines, selected for simple and clear skin care.",
    imageUrl: "/images/foaming-cleanser.png",
    unitPriceSgd: 8.99,
    packQuantity: 30,
    packPriceSgd: 269.7,
    unitWeightKg: 0.23,
    inventoryPacks: 20,
    active: true,
    purchaseEnabled: true,
    sortOrder: 20,
  },
  {
    id: "cleansing-water",
    slug: "cleansing-water",
    name: "J'essence Vegan Cleansing Water",
    category: "cleansing",
    volumeLabel: "300ml",
    shortDescription: "Light cleansing water for quick reset moments.",
    description: "A lightweight cleansing water for light makeup, sunscreen residue and quick daily cleansing.",
    imageUrl: "/images/cleansing-water.png",
    unitPriceSgd: 8.99,
    packQuantity: 30,
    packPriceSgd: 269.7,
    unitWeightKg: 0.34,
    inventoryPacks: 20,
    active: true,
    purchaseEnabled: true,
    sortOrder: 30,
  },
  {
    id: "diffuser-350g",
    slug: "diffuser-350g",
    name: "Volcanic Stone Diffuser",
    category: "diffuser",
    volumeLabel: "350g",
    shortDescription: "Compact volcanic stone scent object for smaller corners.",
    description: "A compact Jeju volcanic stone diffuser with citrus oil, suited for desks, shelves and personal spaces.",
    imageUrl: "/images/diffuser-350g.png",
    unitPriceSgd: 21,
    packQuantity: 20,
    packPriceSgd: 420,
    unitWeightKg: 0.48,
    inventoryPacks: 12,
    active: true,
    purchaseEnabled: true,
    sortOrder: 40,
  },
  {
    id: "diffuser-500g",
    slug: "diffuser-500g",
    name: "Volcanic Stone Diffuser",
    category: "diffuser",
    volumeLabel: "500g",
    shortDescription: "Fuller volcanic stone diffuser for rooms and shared spaces.",
    description: "A larger Jeju volcanic stone diffuser with citrus oil, suited for bedrooms, bathrooms and shared spaces.",
    imageUrl: "/images/diffuser-500g.png",
    unitPriceSgd: 46,
    packQuantity: 20,
    packPriceSgd: 920,
    unitWeightKg: 0.68,
    inventoryPacks: 10,
    active: true,
    purchaseEnabled: true,
    sortOrder: 50,
  },
];
